# Generated by Django 6.1.1 on 2026-09-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('zona', models.CharField(choices=[('comodoro_centro', 'Centro de Comodoro'), ('zona_norte', 'Zona Norte / Km 3'), ('zona_sur', 'Zona Sur / Rada Tilly'), ('otros', 'Otras zonas de Chubut')], default='comodoro_centro', max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('preferencia_contacto', models.CharField(choices=[('email', 'Por email'), ('telefono', 'Por teléfono'), ('whatsapp', 'Por WhatsApp')], max_length=20)),
                ('mensaje', models.TextField(blank=True, help_text='¿Qué tipo de inmueble busca? (Casa, depto, local)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
