# Generated by Django 6.1.1 on 2026-09-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='zona',
            field=models.CharField(choices=[('centro_bajadas', 'Centro / Bajadas 1 a 3'), ('terraza_mar', 'Terraza al Mar / Los Acantilados'), ('barrio_peumayen', 'Barrio Peumayén / Zona Sur'), ('san_antonio', 'San Antonio Oeste'), ('otros', 'Otras zonas')], default='comodoro_centro', max_length=50),
        ),
    ]
