# Generated by Django 6.1.1 on 2026-09-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0002_alter_prospecto_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
