# Generated by Django 6.1.1 on 2026-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0003_prospecto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='tipo_inmueble',
            field=models.CharField(choices=[('depto', 'Departamento'), ('casa', 'Casa'), ('duplex', 'Dúplex'), ('local', 'Local Comercial'), ('terreno', 'Lote / Terreno')], default='depto', max_length=20),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='zona',
            field=models.CharField(choices=[('centro_bajadas', 'Centro / Bajadas 1 a 3'), ('terraza_mar', 'Terraza al Mar / Los Acantilados'), ('barrio_peumayen', 'Barrio Peumayén / Zona Sur'), ('san_antonio', 'San Antonio Oeste'), ('otros', 'Otras zonas')], default='centro_bajadas', max_length=50),
        ),
    ]
